Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;

namespace BlogHost.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult Chat()
        {
            return View();
        }
    }
}

Controllers/PublicationController.cs
using System.Linq;
using System.Threading.Tasks;
using BlogHost.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Entities;
using Interfaces;
using Services;
using ViewModels;

namespace BlogHost.Controllers
{
    public class PublicationController : Controller
    {
        UserManager<User> _userManager;
        IUserService _userService;
        private readonly IUser _user; //заменить
        //private readonly IPublication _publication;
        IPublicationService _publicationService;
        ITopicService _topicService;
        ICommentSevice _commentSevice;
        IVideoService _videoService;
        
        //private readonly ITopic _topic; //заменить
       
        public PublicationController(IVideoService videoService, ICommentSevice commentSevice, UserManager<User> userManager, IUser iUser, IPublicationService iPublication, ITopicService iTopic)
        {
            _videoService = videoService;
            _commentSevice = commentSevice;
            _user = iUser;
            _publicationService = iPublication;
            _topicService = iTopic;
            _userManager = userManager;
        }

        public IActionResult CreatePost()
        {
            return View();
        }

        public async Task<IActionResult> Post(int id)
        {
            Publication post = _publicationService.GetPostDB(id);
            
            ViewBag.Videos = await _videoService.GetAllVideos(post.Id);
            if (post == null)
            {
                return NotFound();
            }
            return View(@post);
        }

        public IActionResult AllPosts(bool flag)
        {
            if (flag)
            {
                return View(_publicationService.AllPostIsFavorite());
            }
            else
            {
                return View(_publicationService.AllPost());
            }
        }

        [HttpGet]
        public IActionResult ThemsPost(string nameTopic)
        {
            return View(_publicationService.AllThemsPost(_topicService.GetIDTopicDB(nameTopic)));
        }

        [HttpGet]
        public IActionResult MyPosts()
        {
            return View(_publicationService.MyPost(_user.GetUserDB(_userManager.GetUserId(User))));
        }

        [HttpPost]
        public IActionResult CreatePost(CreatePublicationViewModel model)
        {
            if (ModelState.IsValid)
            {
                
                var user = _user.GetUserDB(_userManager.GetUserId(User));
                // считываем переданный файл в массив байтов
                

               // string a = _userManager.GetUserId(User);
                var publ = _publicationService.AddPublicationDB(model, user);
                return RedirectToAction("AllPosts");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditPost(int id)
        {
            Publication post = _publicationService.GetPostDB(id);
            if (post == null)
            {
                return NotFound();
            }
            EditePostViewModel model = new EditePostViewModel
            {
                Id = post.Id,
                PublicationName = post.PublicationName,
                PublicationText = post.PublicationText,
                Discription = post.Discription,
                TopicName = _topicService.GetTopicName(post.TopicId)
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(EditePostViewModel model)
        {
            if (ModelState.IsValid)
            {
                Publication post = _publicationService.GetPostDB(model.Id);
                if (post != null)
                {
                    post.PublicationName = model.PublicationName;
                    post.PublicationText = model.PublicationText;
                    post.Discription = model.Discription;
                    post.TopicId = _topicService.GetTopicDB(model.TopicName).Id;
                    post.Topic = _topicService.GetTopicDB(model.TopicName);

                    _publicationService.UpdatePost(post);

                    return RedirectToAction("AllPosts");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Like(int id)
        {
            Publication post = _publicationService.GetLikePost(id);
            return RedirectToAction("Post", new { id = id });
        }


        public async Task<ActionResult> Delete(int id)
        {
            Publication post = _publicationService.GetPostDB(id);
            if (post != null)
            {
                _publicationService.DeletePost(post);
            }
            return RedirectToAction("AllPosts");
        }
    }
}

Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogHost.ViewModels;
using Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BlogHost.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult AdminPanel() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("AdminPanel");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("AdminPanel");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.Where(m => m.Name != "admin").ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Controllers/UsersController.cs
using System.Threading.Tasks;
using BlogHost.ViewModels;
using Entities;
using Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Services;

namespace BlogHost.Controllers
{
    public class UsersController : Controller
    {

        //private IUser @object;
        UserManager<User> _userManager;
        IUserService _userService;
        //private readonly IUser _user; //заменить
        //private readonly IPublication _publication;
        IPublicationService _publicationService;
        ITopicService _topicService;
        //private readonly ITopic _topic; //заменить

        public UsersController(UserManager<User> userManager, IUserService iUser, IPublicationService iPublication, ITopicService iTopic)
        {
            _userService = iUser;
            _publicationService = iPublication;
            _topicService = iTopic;
            _userManager = userManager;
        }
        //public UsersController(IUser @object)
        //{
        //    this.@object = @object;
        //}
        public IActionResult Index()
        {
            return View(_userService.GetAll());
        }


        public IActionResult Profile(){

            return View(_userService.GetUserDB(_userManager.GetUserId(User)));
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, Year = model.Year };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Profile");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public IActionResult GetUser(int? id)
        {
            if (!id.HasValue)
                return BadRequest();
            User user = _userService.GetUserDB("id.Value");
            if (user == null)
                return NotFound();
            return View(user);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Year = user.Year, Gender = user.Gender,
                Name = user.Name, SecondName = user.SecondName, Profession = user.Profession};
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Year = model.Year;
                    user.Name = model.Name;
                    user.SecondName = model.SecondName;
                    user.Profession = model.Profession;
                    user.Gender = model.Gender;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Profile");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Profile");
        }
        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Profile");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogHost</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-4 pt-1">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="text-muted" asp-controller="Users" asp-action="Profile">Profile</a>
                        <a class="text-muted" asp-controller="Publication" asp-action="MyPosts">My posts</a>
                        <a class="text-muted" asp-controller="Publication" asp-action="AllPosts">All posts</a>
                        <a class="text-muted" asp-controller="Publication" asp-action="CreatePost">Create posts</a>
                        <a class="text-muted" asp-controller="Chat" asp-action="Chat">Chat</a>


                        if (User.IsInRole("admin") || User.IsInRole("moder"))
                        {
                            <a class="text-muted" asp-controller="Roles" asp-action="AdminPanel">AP</a>
                        }
                    }
                    else
                    {
                        <a class="text-muted" asp-controller="Account" asp-action="Register">Profile</a>
                        <a class="text-muted" asp-controller="Account" asp-action="Register">My posts</a>
                        <a class="text-muted" asp-controller="Account" asp-action="Register">All posts</a>
                        <a class="text-muted" asp-controller="Account" asp-action="Register">Create posts</a>
                        <a class="text-muted" asp-controller="Account" asp-action="Register">Chat</a>
                    }
                </div>
                <div class="col-4 text-center">
                    <h3><a class="blog-header-logo text-dark" asp-controller="Home" asp-action="Index">BlogHost</a></h3>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center">
                    <a class="text-muted" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
                    </a>
                    <div>
                        @if (User.Identity.IsAuthenticated)
                        {

                            <p>@User.Identity.Name</p>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Account" asp-action="LogOff">LogOff</a>

                        }
                        else
                        {
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Account" asp-action="Login">Sign in</a>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Account" asp-action="Register">Sign up</a>
                        }
                    </div>
                </div>
            </div>
        </header>
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
                @if (User.Identity.IsAuthenticated)
                {

                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="World">World</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="U.S.">U.S.</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Technology">Technology</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Design">Design</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Culture">Culture</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Business">Business</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Politics">Politics</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Opinion">Opinion</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Science">Science</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Health">Health</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Style">Style</a>
                    <a class="p-2 text-muted" asp-controller="Publication" asp-action="ThemsPost" asp-route-nameTopic="Travel">Travel</a>

                }
                else
                {
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="World">World</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="U.S.">U.S.</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Technology">Technology</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Design">Design</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Culture">Culture</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Business">Business</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Politics">Politics</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Opinion">Opinion</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Science">Science</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Health">Health</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Style">Style</a>
                    <a class="p-2 text-muted" asp-controller="Account" asp-action="Register" asp-route-nameTopic="Travel">Travel</a>
                }
            </nav>
        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-black">
            &copy; 2020 - BlogHost - <vk></vk> - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>