Controllers/CommentController.cs
using System.Threading.Tasks;
using BlogHost.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Entities;
using Interfaces;
using Services;
using ViewModels;

namespace BlogHost.Controllers
{
    public class CommentController : Controller
    {
        UserManager<User> _userManager;
        private readonly IUser _user;
        // private readonly IPublication _publication;
        IPublicationService _publicationService;
       // private readonly ITopic _topic;
        ITopicService _topicService;
        //private readonly IComment _comment;
        ICommentSevice _commentService;

        

        public CommentController( UserManager<User> userManager, IUser iUser, IPublicationService iPublication, ITopicService iTopic, ICommentSevice commentService)
        {
            
            _user = iUser;
            _publicationService = iPublication;
            _topicService = iTopic;
            _userManager = userManager;
            _commentService = commentService;
        }

        public static int ID;

        public IActionResult CreateComment(int id)
        {
            ID = id;
            return View();
        }

        [HttpPost]
        public IActionResult CreateComment(CreateCommentViewModel model)
        {
            var login = _user.GetUserDB(_userManager.GetUserId(User)).UserName;

            var comment = _commentService.CreateComment(model, ID, login);
            //Comment comment = new Comment
            //{
            //    CommentText = model.CommentText,
            //    LoginUser =,
            //    PublicationID = ID,
            //    Publication = _publication.GetPostDB(ID)
            //};

            //_comment.AddCommentDB(comment);
            if (comment != null)
                return RedirectToAction("Post", "Publication", new { ID });

            return View(comment);
        }

        [HttpGet]
        public IActionResult AllComments(int id)
        {
            var comments = _commentService.AllComments(id);
            //var count =  _likeService.GetAllLikes( Likes.Where(userLike => userLike.UserId == ViewBag.UserId).Count();
            //return RedirectToAction("Post", "Publication", new { ID });
            return View(comments);
        }

        //кол-во лайков
      
        //public void Hello(int id, int postId) // передаем id комента
        //{
        //    var com = _commentService.AllComments(postId); //айди поста
        //    var likes = _likeService.GetAllLikes(id);
        //    int count = 0;
        //    foreach(var c in com)
        //    {
        //        foreach (var item in likes)
        //        {
        //            count += 1;
        //        }
        //        c.polelike = count;

        //    }                 

        //}

        [HttpGet]
        public async Task<IActionResult> EditComment(int id)
        {
            Comment comment = _commentService.GetCommentDB(id);
            if (comment == null)
            {
                return NotFound();
            }
            CreateCommentViewModel model = new CreateCommentViewModel
            {
                CommentText = comment.CommentText
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditComment(CreateCommentViewModel model, int id)
        {
            if (ModelState.IsValid)
            {
                Comment comment = _commentService.GetCommentDB(id);
                if (comment != null)
                {
                    //comment.CommentText = model.CommentText;
                    //_comment.UpdateComment(comment);

                    comment = _commentService.EditComment(model,comment);
                    return RedirectToAction("AllComments");
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Delete(int id)
        {
            Comment comment = _commentService.GetCommentDB(id);
            if (comment != null)
            {
                _commentService.DeleteComment(comment);
            }
            return RedirectToAction("AllComments");
        }
    }
}

Controllers/PublicationController.cs
using System.Linq;
using System.Threading.Tasks;
using BlogHost.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Entities;
using Interfaces;
using Services;
using ViewModels;

namespace BlogHost.Controllers
{
    public class PublicationController : Controller
    {
        UserManager<User> _userManager;
        IUserService _userService;
        private readonly IUser _user; //заменить
        //private readonly IPublication _publication;
        IPublicationService _publicationService;
        ITopicService _topicService;
        ICommentSevice _commentSevice;
        IVideoService _videoService;
        
        //private readonly ITopic _topic; //заменить
       
        public PublicationController(IVideoService videoService, ICommentSevice commentSevice, UserManager<User> userManager, IUser iUser, IPublicationService iPublication, ITopicService iTopic)
        {
            _videoService = videoService;
            _commentSevice = commentSevice;
            _user = iUser;
            _publicationService = iPublication;
            _topicService = iTopic;
            _userManager = userManager;
        }

        public IActionResult CreatePost()
        {
            return View();
        }

        public async Task<IActionResult> Post(int id)
        {
            Publication post = _publicationService.GetPostDB(id);
            
            ViewBag.Videos = await _videoService.GetAllVideos(post.Id);
            if (post == null)
            {
                return NotFound();
            }
            return View(@post);
        }

        public IActionResult AllPosts(bool flag)
        {
            if (flag)
            {
                return View(_publicationService.AllPostIsFavorite());
            }
            else
            {
                return View(_publicationService.AllPost());
            }
        }

        [HttpGet]
        public IActionResult ThemsPost(string nameTopic)
        {
            return View(_publicationService.AllThemsPost(_topicService.GetIDTopicDB(nameTopic)));
        }

        [HttpGet]
        public IActionResult MyPosts()
        {
            return View(_publicationService.MyPost(_user.GetUserDB(_userManager.GetUserId(User))));
        }

        [HttpPost]
        public IActionResult CreatePost(CreatePublicationViewModel model)
        {
            if (ModelState.IsValid)
            {
                
                var user = _user.GetUserDB(_userManager.GetUserId(User));
                // считываем переданный файл в массив байтов
                

               // string a = _userManager.GetUserId(User);
                var publ = _publicationService.AddPublicationDB(model, user);
                return RedirectToAction("AllPosts");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditPost(int id)
        {
            Publication post = _publicationService.GetPostDB(id);
            if (post == null)
            {
                return NotFound();
            }
            EditePostViewModel model = new EditePostViewModel
            {
                Id = post.Id,
                PublicationName = post.PublicationName,
                PublicationText = post.PublicationText,
                Discription = post.Discription,
                TopicName = _topicService.GetTopicName(post.TopicId)
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(EditePostViewModel model)
        {
            if (ModelState.IsValid)
            {
                Publication post = _publicationService.GetPostDB(model.Id);
                if (post != null)
                {
                    post.PublicationName = model.PublicationName;
                    post.PublicationText = model.PublicationText;
                    post.Discription = model.Discription;
                    post.TopicId = _topicService.GetTopicDB(model.TopicName).Id;
                    post.Topic = _topicService.GetTopicDB(model.TopicName);

                    _publicationService.UpdatePost(post);

                    return RedirectToAction("AllPosts");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Like(int id)
        {
            Publication post = _publicationService.GetLikePost(id);
            return RedirectToAction("Post", new { id = id });
        }


        public async Task<ActionResult> Delete(int id)
        {
            Publication post = _publicationService.GetPostDB(id);
            if (post != null)
            {
                _publicationService.DeletePost(post);
            }
            return RedirectToAction("AllPosts");
        }
    }
}

Controllers/VideosController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Services;
using ViewModels;
using Entities;

namespace BlogHost.Controllers
{
    
    public class VideosController : Controller
    {
        //private readonly CourseDbContext _context;
        //private readonly IVideo _video;
        IVideoService _videService;
       public VideosController(/*CourseDbContext context*/ IVideoService videoService)///, IVideo video)
        {
            //_video = video;
            _videService = videoService;
           // _context = context;
        }

        //public async Task<IActionResult> Index()
        //{
        //    //var appDbContext = _context.Videos.Include(v => v.Module);
        //    return View(await _videService.GetAllVideos());
        //}

        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _videService.GetVideo(id);

            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

       
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
      
        public async Task<IActionResult> Create(int id, VideoViewModel video)//[Bind("Id,Name,Url")] Video video)
        {
            if (ModelState.IsValid)
            {
                Video new_video = await _videService.AddVideo(id, video);

                if(new_video != null)
                    return RedirectToAction("Post", "Publication", new { id = new_video.PublicationId });
            }
           
            return View(video);
        }

      
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _videService.GetVideo(id);
            if (video == null)
            {
                return NotFound();
            }
            return View(video);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Edit(int id, VideoViewModel video)
        {
            if (ModelState.IsValid)
            {
                Video v = await _videService.EditVideo(id, video);
                if(v != null)
                    return RedirectToAction("Post", "Publication", new { id = v.PublicationId });                
            }            
            return View(video);
        }

       
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _videService.GetVideo(id);
            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> DeleteConfirmed(int id)
        {    
            var video = await _videService.GetVideo(id);              
            await _videService.DeleteVideoById(id);           
            return RedirectToAction("Post", "Publication", new { id = video.PublicationId });
        }

       
    }
}

Views/Publication/AllPosts.cshtml
@model IEnumerable<Publication>
@{ ViewData["Title"] = "AllPosts"; }

<style>
    p1 {
        padding: 20px;
    }
</style>

<div>
    <h1 class="text-center">AllPosts</h1>

    <a class="btn btn-sm btn-primary text-center" asp-controller="Publication" asp-action="AllPosts" asp-route-flag="@true">Показать любимые</a>
    <br />
</div>
<br />



@foreach (var post in Model)
{
<div class="container row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col-auto d-none d-lg-block">
        <img src="data:image/jpeg;base64,@(Convert.ToBase64String(@post.AvatarPost))" align="right" width="300" height="322" />
    </div>
    <div class="col p-4 d-flex flex-column position-static">
        <h5 class="card-title">@post.PublicationName</h5>
        <p>@post.Discription</p>
        <p>@post.DatePublication</p>
        <p><a class="button" asp-controller="Publication" asp-action="Post" asp-route-id="@post.Id">Continue reading...</a></p>
    </div>
</div>}


<br />

Views/Publication/CreatePost.cshtml
@model ViewModels.CreatePublicationViewModel

@{ ViewData["Title"] = "CreatePost"; }

<div class="text-center container col-4">
    <h1>Create post</h1>
    <form class="shadow p-3 mb-5 bg-white rounded" method="post" asp-controller="Publication" asp-action="CreatePost" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly"></div>
        <div>
            <label asp-for="PublicationName"></label><br />
            <input asp-for="PublicationName" maxlength="40" />
            <span asp-validation-for="PublicationName"></span>
        </div>
        <div>
            <label asp-for="Discription"></label><br />
            <input asp-for="Discription" maxlength="110" />
            <span asp-validation-for="Discription"></span>
        </div>
        <div>
            <label asp-for="PublicationText"></label><br />
            <textarea asp-for="PublicationText" cols="40" rows="3"></textarea>
            <span asp-validation-for="PublicationText"></span>
        </div>
        <div class="form-group">
            <p>
                <label>Фото</label>
                <input name="AvatarPost" type="file" class="form-control" />
                <input name="AvatarPost2" type="file" class="form-control" />
            </p>
        </div>
        <div>
            <label asp-for="isFavorite"></label><br />
            <input asp-for="isFavorite" />
        </div>
        <select asp-for="TopicName" size="1">
            <option value="World">World</option>
            <option selected="selected" value="U.S.">U.S.</option>
            <option value="Technology">Technology</option>
            <option value="Design">Design</option>
            <option value="Culture">Culture</option>
            <option value="Business">Business</option>
            <option value="Politics">Politics</option>
            <option value="Opinion">Opinion</option>
            <option value="Science">Science</option>
            <option value="Health">Health</option>
            <option value="Style">Style</option>
            <option value="Travel">Travel</option>
        </select>
        <div class="">
            <input class="btn btn-sm btn-primary btn-block" type="submit" value="Создать" />
        </div>
    </form>
</div>

Views/Publication/EditPost.cshtml
@model BlogHost.ViewModels.EditePostViewModel

@{
    ViewData["Title"] = "EditPost";
}

<h1>EditPost</h1>
<div class="text-center container col-4">
    <form method="post" asp-controller="Publication" asp-action="EditPost">
        <div asp-validation-summary="ModelOnly"></div>
        <div>
            <label asp-for="PublicationName"></label><br />
            <input asp-for="PublicationName" />
            <span asp-validation-for="PublicationName"></span>
        </div>
        <div>
            <label asp-for="Discription"></label><br />
            <input asp-for="Discription" />
            <span asp-validation-for="Discription"></span>
        </div>
        <div>
            <label asp-for="PublicationText"></label><br />
            <textarea asp-for="PublicationText" cols="40" rows="3"></textarea>
            <span asp-validation-for="PublicationText"></span>
        </div>
        <select asp-for="TopicName" size="1">
            <option value="World">World</option>
            <option selected="selected" value="U.S.">U.S.</option>
            <option value="Technology">Technology</option>
            <option value="Design">Design</option>
            <option value="Culture">Culture</option>
            <option value="Business">Business</option>
            <option value="Politics">Politics</option>
            <option value="Opinion">Opinion</option>
            <option value="Science">Science</option>
            <option value="Health">Health</option>
            <option value="Style">Style</option>
            <option value="Travel">Travel</option>
        </select>
        <div class="">
            <input class="btn btn-sm btn-primary btn-block" type="submit" value="Создать" />
        </div>
    </form>
</div>

Views/Publication/MyPosts.cshtml
@model IEnumerable<Entities.Publication>
@{
    ViewData["Title"] = "MyPosts";
}

<h1 class="text-center">MyPosts</h1>
@foreach (var post in Model)
{
    <div class="card bg-dark text-white">
        <img style="height:300px;" src="data:image/jpeg;base64,@(Convert.ToBase64String(@post.AvatarPost))" alt="" class="card-img" />
        <div class="card-img-overlay">
            <h5 class="card-title">@post.PublicationName</h5>
            <p class="card-text">@post.Discription</p>
            <p class="card-text">@post.DatePublication</p>
            <p class="card-text"><a class="text-white font-weight-bold" asp-controller="Publication" asp-action="Post" asp-route-id="@post.Id">Continue reading...</a></p>
        </div>
    </div>
    <br />
}

Views/Publication/Post.cshtml
@model Entities.Publication

@{ ViewData["Title"] = "Post"; }

<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
                <table>
                    <tr>
                        <td>
                            <p class="lead">@Model.PublicationName</p>

                            <!-- A Real Hero (and a real human being) -->
                            <p>
                                <img style='width:500px; height:400px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(@Model.AvatarPost))" alt="" class="img-rounded" />
                                <img style='width:500px; height:400px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(@Model.AvatarPost2))" alt="" class="card-img" />
                            </p><!-- /hero -->
                            <!-- Callout Panel -->
                            <p class="callout">
                                @Model.DatePublication
                            </p>

                            <a label id="LIKEpost" asp-controller="Publication" asp-action="Like" asp-route-id="@Model.Id">LIKE</a>
                            <label id="likePost" asp-for="LikePost">@Model.LikePost</label>
                            @*<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
                                <script type="text/javascript">

                                     if (LIKEpost) {
                                          $.ajax({
                                               type = 'POST',
                                               url: '@Url.Action("Like", "Publication")',
                                               data: {
                                                   id: @Model.Id
                                               },
                                               dataType: "text",
                                               success: function (msg) {
                                                    let likePost = getElementById('likePost');
                                                    likePost++;
                                                    location.reload(likePost);
                                                    console.log(msg);
                                               },
                                               error: function (req, status, error) {
                                                    console.log(msg);
                                               }
                                          });
                                     }
                                </script>*@

                            <p>@Model.PublicationText</p>
                            <br />
                            <br />
                        </td>
                    </tr>
                </table>
                <a class="btn btn-sm btn-primary" asp-controller="Comment" asp-action="CreateComment" asp-route-id="@Model.Id">Оставить комментарий</a>
                <a class="btn btn-sm btn-primary" asp-controller="Comment" asp-action="AllComments" asp-route-id="@Model.Id">Просмотреть комментарии</a>


                <a class="button-active revealator-slideup revealator-delay3" asp-controller="Videos" asp-action="Create" asp-route-id="@Model.Id">
                    Новый видос
                </a>

                @if (User.IsInRole("admin") || User.IsInRole("moder"))
                {
    <a class="btn btn-sm btn-primary" asp-controller="Publication" asp-action="EditPost" asp-route-id="@Model.Id">Редактировать публикацию</a>
                    <a class="btn btn-sm btn-danger" asp-controller="Publication" asp-action="Delete" asp-route-id="@Model.Id">Удалить публикацию</a>}
            </div>

        </td>
        <td></td>
    </tr>
</table>


<div class="col-md-8">
    @if (@Model.Videos != null)
    {

@foreach (var v in @ViewBag.Videos)
{
<div class="blog-post">
    <h2 class="blog-post-title text-white"><a name="@v.Id">@v.Name</a></h2>

    <video width="640" height="480" controls>
        <source src=@v.Url type="video/mp4">
        Your browser does not support the video tag.
    </video>


    <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
            <a class="btn btn-sm btn-outline-secondary" role="button" asp-controller="Videos" asp-action="Edit" asp-route-id="@v.Id">
                Изменить
            </a>

            <form asp-controller="Videos" asp-action="Delete" asp-route-id="@v.Id" method="post">

                <button type="submit" class="btn btn-sm btn-danger">
                    Удалить
                </button>
            </form>
        </div>
    </div>


</div>}}
            </div>

Views/Publication/ThemsPost.cshtml
@model IEnumerable<Entities.Publication>
@{
    ViewData["Title"] = "ThemsPost";
}

<h2 class="text-center">Posts</h2>
@foreach (var post in Model)
{
    <div class="card bg-dark text-white">
        <img style="height:300px;" src="data:image/jpeg;base64,@(Convert.ToBase64String(@post.AvatarPost))" alt="" class="card-img" />
        <div class="card-img-overlay">
            <h5 class="card-title">@post.PublicationName</h5>
            <p class="card-text">@post.Discription</p>
            <p class="card-text">@post.DatePublication</p>
            <p class="card-text"><a class="text-white font-weight-bold" asp-controller="Publication" asp-action="Post" asp-route-id="@post.Id">Continue reading...</a></p>
        </div>
    </div>
    <br />
}